development:
  adapter: postgresql
  encoding: unicode
  database: location_development
  pool: 5
  username: root
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: location_test
  pool: 5
  username: root
  password: root